server:
  port: 9001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "1ca67cbccbbcba715a9dd252fc221741ef808143ba94d7b01d717b0389bd4ea4f680250033cfd457d1d0a1c9a79046bde8771a1d24345a3b63695787b466be2d"
  application:
    name: "crediya-registro-usuarios"
  devtools:
    add-properties: false
  r2dbc:
    host: localhost
    port: 5432
    database: crediya-registro-usuarios
    schema: public
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    co.com.pragma: TRACE

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"