server:
  port: 9001

spring:
  application:
    name: "crediya-registro-usuarios"
  devtools:
    add-properties: false
  r2dbc:
    host: localhost
    port: 5432
    database: crediya-registro-usuarios
    schema: public
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    co.com.pragma: TRACE

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"